import smtplib
from email.message import EmailMessage


def Submit(receiver):
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    # Make sure to give app access in your Google account
    server.login('teamgofitatw@gmail.com', 'abcdefg0987')
    email = EmailMessage()
    email['From'] = 'teamgofitatw@gmail.com'
    email['To'] = receiver
    email['Subject'] = "Form Submitted"

    message = f''' 
    Dear Customer,
        We will contact you shortly.We appreciate your submission to GoFit by {receiver}
        Go to http://127.0.0.1:5000 to login.

        This is a autogenerated message.Please do not reply to this email.

    Best regards,
    GoFit Team

'''
    email.set_content(message)
    server.send_message(email)


if __name__ == '__main__':
    Submit('cecilagaming@gmail.com')
    print("Form Sent.")
